/**
 * Markdown exporter for mcp-label reports.
 */

import type { McpLabelReport } from '../types.js';
import { summarizeConcerns } from '../utils/index.js';

export function exportMarkdown(report: McpLabelReport): string {
  const lines: string[] = [];

  lines.push('# MCP Safety Label');
  lines.push('');
  if (report.summary.capabilityImpact) {
    lines.push(`Capability impact: **${capitalize(report.summary.capabilityImpact)}**`);
    lines.push(`Effective risk: **${capitalize(report.summary.effectiveRisk!)}**`);
    lines.push(`Hardening grade: **${report.summary.hardeningGrade}**`);
    lines.push(`Publisher trust: **${capitalize(report.summary.publisherTrust!)}**`);
    lines.push(`Install hygiene: **${report.summary.installHygiene}**`);
    lines.push(`Config hardening: **${report.summary.configHardening}**`);
    lines.push(`Static confidence: **${capitalize(report.summary.analysisConfidence!)}**`);
  } else {
    lines.push(`Overall grade: **${report.summary.overallGrade}**`);
    lines.push(`Overall risk: **${capitalize(report.summary.overallRisk)}**`);
  }
  lines.push(`Static analysis only: **${report.source.staticOnly ? 'Yes' : 'No'}**`);
  lines.push('');

  // Summary table
  if (report.servers[0]?.capabilityImpact) {
    lines.push('| Server | Impact | Risk | Hardening | Trust | Main concerns |');
    lines.push('|---|:---:|:---:|:---:|:---:|---|');
    for (const server of report.servers) {
      const concerns = summarizeConcerns(server.permissions, server.installRisks, 4);
      lines.push(
        `| ${server.name} | ${capitalize(server.capabilityImpact!)} | ${capitalize(server.effectiveRisk!)} | ${server.hardeningGrade} | ${capitalize(server.publisherTrust!)} | ${concerns.join(', ') || 'none'} |`,
      );
    }
  } else {
    lines.push('| Server | Grade | Risk | Main concerns |');
    lines.push('|---|:---:|:---:|---|');
    for (const server of report.servers) {
      const concerns = summarizeConcerns(server.permissions, server.installRisks, 4);
      lines.push(
        `| ${server.name} | ${server.grade} | ${capitalize(server.risk)} | ${concerns.join(', ') || 'none'} |`,
      );
    }
  }
  lines.push('');

  // Per-server sections
  for (const server of report.servers) {
    lines.push(`## ${server.name}`);
    lines.push('');

    if (server.knownServerProfile && server.publisherTrust) {
      lines.push(`> Known server: publisher trust is **${capitalize(server.publisherTrust)}**.`);
      lines.push('');
    }

    const expected = server.permissions.filter((p) => p.expectation === 'expected');
    const unexpected = server.permissions.filter((p) => p.expectation === 'unexpected');
    const unknown = server.permissions.filter((p) => p.expectation === 'unknown');

    if (expected.length > 0) {
      lines.push('### Expected Capabilities');
      lines.push('');
      for (const perm of expected) {
        lines.push(
          `- **${capitalize(perm.level)}:** \`${perm.permission}\` — ${perm.explanation}`,
        );
      }
      lines.push('');
    }

    if (unexpected.length > 0) {
      lines.push('### Unexpected or Review-Needed Capabilities');
      lines.push('');
      for (const perm of unexpected) {
        lines.push(
          `- **${capitalize(perm.level)}:** \`${perm.permission}\` — ${perm.evidence}`,
        );
      }
      lines.push('');
    }

    if (unknown.length > 0) {
      lines.push('### Permissions');
      lines.push('');
      for (const perm of unknown) {
        lines.push(
          `- **${capitalize(perm.level)}:** \`${perm.permission}\` — ${perm.evidence}`,
        );
      }
      lines.push('');
    }

    if (server.installRisks.length > 0) {
      lines.push('### Install Risks');
      lines.push('');
      for (const risk of server.installRisks) {
        lines.push(
          `- **${capitalize(risk.level)}:** \`${risk.id}\` — ${risk.explanation}`,
        );
      }
      lines.push('');
    }

    if (server.recommendations.length > 0) {
      lines.push('### Recommendations');
      lines.push('');
      for (const rec of server.recommendations) {
        lines.push(`- ${rec}`);
      }
      lines.push('');
    }

    if (server.policyResults && server.policyResults.length > 0) {
      const failed = server.policyResults.filter((r) => !r.passed);
      if (failed.length > 0) {
        lines.push('### Policy Violations');
        lines.push('');
        for (const r of failed) {
          lines.push(`- ❌ **${r.ruleId}:** ${r.details}`);
        }
        lines.push('');
      }
    }

    // Why this result?
    if (server.scoringTrace) {
      lines.push('### Why this result?');
      lines.push('');
      lines.push(server.scoringTrace.explanation);
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('');
  lines.push(
    '*Generated by [mcp-label](https://github.com/mcp-label/mcp-label). High capability impact does not mean a server is malicious. This is a heuristic analysis, not a proof of safety.*',
  );

  return lines.join('\n');
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}
